services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-chat
    restart: unless-stopped
    ports:
      - '5004:3000'
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true